services:
  - type: web
    name: campusxconnect-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: campusxconnect-db
          property: connectionString
      - key: JWT_SECRET
        sync: false

databases:
  - name: campusxconnect-db
    plan: free
